import { test, expect, _electron as electron } from '@playwright/test';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

// The header title's basename must mirror the timestamped-saves setting:
// stripped of a generated `_yyyymmdd_HHMMSS` suffix while the feature is on
// (src/main/timestamped-save-path.js owns that format), left exactly as
// chosen while it is off, since an off-feature suffix was never generated by
// NoirDraft and isn't safe to treat as one.

test('editor title strips the timestamp suffix while timestamped saves are enabled', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'noirdraft-e2e-title-on-'));
  const filePath = path.join(directory, 'story.md');
  const application = await electron.launch({
    args: [path.resolve('.')],
    env: {
      ...process.env,
      ELECTRON_DISABLE_SECURITY_WARNINGS: 'true',
      NOIRDRAFT_E2E_ALLOWED_PATH: filePath,
      NOIRDRAFT_E2E_PREFERENCES_PATH: path.join(directory, 'preferences.json'),
    },
  });
  try {
    const window = await application.firstWindow();
    await window.waitForFunction(() => Boolean(window.__noirDraftTest?.getCommitController()));
    await window.waitForFunction(
      () => document.querySelector('[data-toggle-timestamped-saves]')?.getAttribute('aria-pressed') === 'true',
    );
    const title = await window.evaluate(async (target) => {
      const app = window.__noirDraftTest;
      const contents = app.buildProjectContents();
      const result = await window.noirDraft.documents.save({ filePath: target, contents });
      await app.loadDocument(result.document);
      return document.querySelector('#editor-title').textContent;
    }, filePath);
    expect(title).toBe('story');
  } finally {
    await application.close();
    await rm(directory, { recursive: true, force: true });
  }
});

test('editor title keeps a timestamp-shaped name as-is while timestamped saves are disabled', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'noirdraft-e2e-title-off-'));
  const filePath = path.join(directory, 'story_20260101_120000.md');
  const preferencesPath = path.join(directory, 'preferences.json');
  await writeFile(preferencesPath, JSON.stringify({ saveTimestampedCopies: false }), 'utf8');
  const application = await electron.launch({
    args: [path.resolve('.')],
    env: {
      ...process.env,
      ELECTRON_DISABLE_SECURITY_WARNINGS: 'true',
      NOIRDRAFT_E2E_ALLOWED_PATH: filePath,
      NOIRDRAFT_E2E_PREFERENCES_PATH: preferencesPath,
    },
  });
  try {
    const window = await application.firstWindow();
    await window.waitForFunction(() => Boolean(window.__noirDraftTest?.getCommitController()));
    await window.waitForFunction(
      () => document.querySelector('[data-toggle-timestamped-saves]')?.getAttribute('aria-pressed') === 'false',
    );
    const title = await window.evaluate(async (target) => {
      const app = window.__noirDraftTest;
      const contents = app.buildProjectContents();
      const result = await window.noirDraft.documents.save({ filePath: target, contents });
      await app.loadDocument(result.document);
      return document.querySelector('#editor-title').textContent;
    }, filePath);
    expect(title).toBe('story_20260101_120000');
  } finally {
    await application.close();
    await rm(directory, { recursive: true, force: true });
  }
});
